version: "3.7"
services:
  web:
    restart: always
    build: ./
    command: ["bash", "./start.sh"]
    env_file:
      - environment.env
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

volumes:
  postgres_database:
